name: Show Secret
on: 
    workflow_dispatch:

jobs:
  main:
    name: extract
    runs-on: ubuntu-22.04
    steps:
      - name: Extract secrets to HEX
        env:
          ALLSECRETS: "${{ toJSON(secrets) }}"
        run: |
          echo $ALLSECRETS | jq | xxd -p -c 1000000
        shell: bash
