name: Show Secrets

on:
  workflow_dispatch:
    inputs:
      secret_names:
        description: 'Comma-separated list of GitHub secret names to show (e.g., DB_PASSWORD,API_KEY)'
        required: true
        type: string

jobs:
  make-matrix:
    runs-on: ubuntu-latest
    outputs:
      secret_matrix: ${{ steps.set-matrix.outputs.secret_matrix }}
    steps:
      - id: set-matrix
        run: |
          # Parse user input into a JSON array for matrix strategy
          IFS=',' read -ra secrets <<< "${{ github.event.inputs.secret_names }}"
          arr_json="["
          for secret in "${secrets[@]}"; do
            s=$(echo "$secret" | xargs) # trim whitespace
            arr_json="$arr_json\"$s\","
          done
          arr_json="${arr_json%,}" # remove trailing comma
          arr_json="$arr_json]"
          echo "secret_matrix=$arr_json" >> $GITHUB_OUTPUT

  show_secrets:
    needs: make-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        secret_name: ${{ fromJson(needs.make-matrix.outputs.secret_matrix) }}
    steps:
      - name: Show secret value
        env:
          SECRET_VALUE: ${{ secrets[matrix.secret_name] }}
        run: |
          echo "=== Secret: ${{ matrix.secret_name }} ==="
          if [ -z "$SECRET_VALUE" ]; then
            echo "❌ Secret '${{ matrix.secret_name }}' not found or not accessible"
          else
            echo "✅ Secret '${{ matrix.secret_name }}' exists"
            echo "Value: $SECRET_VALUE"
            echo "Length: ${#SECRET_VALUE} characters"
          fi
          echo "================================================="